# Generated by Django 4.1.4 on 2022-12-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabledata', '0002_help'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help',
            new_name='helps',
        ),
    ]
